# Generated by Django 3.0.3 on 2020-02-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tour_destinations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=200, unique=True)),
                ("tour_title", models.CharField(max_length=250)),
                ("description", models.TextField(max_length="")),
                ("image", models.ImageField(blank=True, upload_to="product")),
                ("location", models.CharField(max_length=250)),
                ("booking_start_date", models.DateField()),
                ("booking_end_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
