# Generated by Django 3.0.3 on 2020-02-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_destinations',
            name='description',
            field=models.TextField(),
        ),
    ]
