# Generated by Django 3.0.3 on 2020-02-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_store', '0003_auto_20200225_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_destinations',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
