# Generated by Django 3.0.3 on 2020-02-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_store', '0004_auto_20200225_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tour_destinations',
            new_name='Destinations',
        ),
    ]
