# Generated by Django 3.0.3 on 2020-03-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour_store", "0006_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="comment",
        ),
    ]
