# Generated by Django 3.0.3 on 2020-04-19 23:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour_store", "0008_auto_20200419_2317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinations",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
