name: Training github actions

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      # First step
      - name: First test
        run: echo "Hello World"

      # Second step
      - name: Second test
        run: echo "Done, Goodbye World"